version: "3.9"

services:
  db:
    image: postgres
    container_name: nodelab_postgres
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodelab
      - POSTGRES_HOST=db
  backend:
    build:
      context: .
    ports:
      - "8010:80"
    depends_on:
      - db