version: "3.9"

services:
  db:
    image: postgres
    container_name: nodelab_postgres
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodelab
      - POSTGRES_HOST=db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - db
volumes:
  postgres-data:

